version: '2'
services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - meg-dev
  php:
    build: php
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - meg-dev
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - meg-dev
networks:
  meg-dev:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"